# Pre-commit hooks for DataDecider
# Install with: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast                 # Check Python AST
      - id: check-builtin-literals    # Check builtin literals
      - id: check-case-conflict       # Check case conflicts
      - id: check-docstring-first     # Check docstring first
      - id: check-merge-conflict      # Check merge conflicts
      - id: check-yaml                # Check YAML syntax
      - id: check-toml                # Check TOML syntax
      - id: debug-statements          # Check debug statements
      - id: end-of-file-fixer         # Fix end of files
      - id: trailing-whitespace       # Fix trailing whitespace
      - id: mixed-line-ending         # Fix mixed line endings

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        args: ['-r', 'data_decide', '-ll', '-s', 'B324,B605,B614']  # Skip known issues
        pass_filenames: false

# Configuration
default_language_version:
  python: python3
